/**
 * Groomer Service
 * API для будущей GroomCRM или назовите ее уже как-нибудь. На этой странице расписаны основные эндпоинты, по которым можно получить данные из базы данных (или положить их туда, если будет такая возможность). Также здесь можно будет протестировать эти самые эндпоинты, посмотреть ответы и всякое такое.  TODO: 1. Обновить структуру описания в соответствии со структурой БД 2. Подготовить возможность тестирования 3. Добавить тест-кейсы для всего API  ### Changelog  **v1.2.1**: Добавил эндпоинт для получения информации об авторизованном Клиенте/Мастере  **v1.2.0**: Обновлены пути, респонсы, эндпоинты для приложений вынесены в отдельный стек  **v1.1.4**: Обновил структуру WorkingDiapason  **v1.1.3**: Добавил описания возвращаемых кодов.  **v1.1.2**: Удалил упоминания Питомцев и Пушей из АПИ  **v1.1.1**: Добавил параметр \"платформа\" для заказа, заменил OneSignal на FCM + APNs  **v1.1.0**: Убрал пуши из API  **v1.0.4**: добавлены фильтры по датам, добавлено поле телефона для мастеров (для смс-оповещений), добавлено поле push_device_id для отправки пушей на телефон. 
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: kosolapus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineResponse2003 from '../model/InlineResponse2003';
import WorkingDiapason from '../model/WorkingDiapason';

/**
* WorkingDiapason service.
* @module api/WorkingDiapasonApi
* @version 1.2.1
*/
export default class WorkingDiapasonApi {

    /**
    * Constructs a new WorkingDiapasonApi. 
    * @alias module:api/WorkingDiapasonApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the clientClientMasterMasterWorkingDiapasonGet operation.
     * @callback module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение расписания мастера
     * Store *WorkingDiapason* entity
     * @param {Number} master Id мастера
     * @param {Number} client ID салона
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Как много элементов должно возвращаться за один запрос (default to 25)
     * @param {Number} opts.offset Смещение от первого (default to 0)
     * @param {String} opts.dateStart Начало периода
     * @param {String} opts.dateEnd Конец периода
     * @param {module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    clientClientMasterMasterWorkingDiapasonGet(master, client, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'master' is set
      if (master === undefined || master === null) {
        throw new Error("Missing the required parameter 'master' when calling clientClientMasterMasterWorkingDiapasonGet");
      }
      // verify the required parameter 'client' is set
      if (client === undefined || client === null) {
        throw new Error("Missing the required parameter 'client' when calling clientClientMasterMasterWorkingDiapasonGet");
      }

      let pathParams = {
        'master': master,
        'client': client
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'date_start': opts['dateStart'],
        'date_end': opts['dateEnd']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2003;
      return this.apiClient.callApi(
        '/client/{client}/master/{master}/working-diapason', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientMasterMasterWorkingDiapasonPost operation.
     * @callback module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {module:model/WorkingDiapason} workingDiapason Store *WorkingDiapason* entity
     * @param {module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    clientClientMasterMasterWorkingDiapasonPost(workingDiapason, callback) {
      let postBody = workingDiapason;
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientMasterMasterWorkingDiapasonPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuthMaster'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/client/{client}/master/{master}/working-diapason', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientMasterMasterWorkingDiapasonWorkingDiapasonDelete operation.
     * @callback module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonWorkingDiapasonDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {Number} master Id мастера
     * @param {Number} client ID салона
     * @param {Number} workingDiapason Id requested WorkingDiapason
     * @param {module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonWorkingDiapasonDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    clientClientMasterMasterWorkingDiapasonWorkingDiapasonDelete(master, client, workingDiapason, callback) {
      let postBody = null;
      // verify the required parameter 'master' is set
      if (master === undefined || master === null) {
        throw new Error("Missing the required parameter 'master' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonDelete");
      }
      // verify the required parameter 'client' is set
      if (client === undefined || client === null) {
        throw new Error("Missing the required parameter 'client' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonDelete");
      }
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonDelete");
      }

      let pathParams = {
        'master': master,
        'client': client,
        'working-diapason': workingDiapason
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuthMaster'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/client/{client}/master/{master}/working-diapason/{working-diapason}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientMasterMasterWorkingDiapasonWorkingDiapasonGet operation.
     * @callback module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonWorkingDiapasonGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение деталей временного отрезка
     * 
     * @param {Number} master Id мастера
     * @param {Number} client ID салона
     * @param {Number} workingDiapason Id requested WorkingDiapason
     * @param {module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonWorkingDiapasonGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    clientClientMasterMasterWorkingDiapasonWorkingDiapasonGet(master, client, workingDiapason, callback) {
      let postBody = null;
      // verify the required parameter 'master' is set
      if (master === undefined || master === null) {
        throw new Error("Missing the required parameter 'master' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonGet");
      }
      // verify the required parameter 'client' is set
      if (client === undefined || client === null) {
        throw new Error("Missing the required parameter 'client' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonGet");
      }
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonGet");
      }

      let pathParams = {
        'master': master,
        'client': client,
        'working-diapason': workingDiapason
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/client/{client}/master/{master}/working-diapason/{working-diapason}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatch operation.
     * @callback module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {Number} master Id мастера
     * @param {Number} client ID салона
     * @param {Number} workingDiapason Id requested WorkingDiapason
     * @param {module:model/WorkingDiapason} workingDiapason Optional description in *Markdown*
     * @param {module:api/WorkingDiapasonApi~clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatch(master, client, workingDiapason, workingDiapason, callback) {
      let postBody = workingDiapason;
      // verify the required parameter 'master' is set
      if (master === undefined || master === null) {
        throw new Error("Missing the required parameter 'master' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatch");
      }
      // verify the required parameter 'client' is set
      if (client === undefined || client === null) {
        throw new Error("Missing the required parameter 'client' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatch");
      }
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatch");
      }
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientMasterMasterWorkingDiapasonWorkingDiapasonPatch");
      }

      let pathParams = {
        'master': master,
        'client': client,
        'working-diapason': workingDiapason
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuthMaster'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/client/{client}/master/{master}/working-diapason/{working-diapason}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
