/**
 * Groomer Service
 * API для будущей GroomCRM или назовите ее уже как-нибудь. На этой странице расписаны основные эндпоинты, по которым можно получить данные из базы данных (или положить их туда, если будет такая возможность). Также здесь можно будет протестировать эти самые эндпоинты, посмотреть ответы и всякое такое.  TODO: 1. Обновить структуру описания в соответствии со структурой БД 2. Подготовить возможность тестирования 3. Добавить тест-кейсы для всего API  ### Changelog  **v1.2.1**: Добавил эндпоинт для получения информации об авторизованном Клиенте/Мастере  **v1.2.0**: Обновлены пути, респонсы, эндпоинты для приложений вынесены в отдельный стек  **v1.1.4**: Обновил структуру WorkingDiapason  **v1.1.3**: Добавил описания возвращаемых кодов.  **v1.1.2**: Удалил упоминания Питомцев и Пушей из АПИ  **v1.1.1**: Добавил параметр \"платформа\" для заказа, заменил OneSignal на FCM + APNs  **v1.1.0**: Убрал пуши из API  **v1.0.4**: добавлены фильтры по датам, добавлено поле телефона для мастеров (для смс-оповещений), добавлено поле push_device_id для отправки пушей на телефон. 
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: kosolapus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineResponse2002 from '../model/InlineResponse2002';
import WorkingDiapason from '../model/WorkingDiapason';

/**
* WorkingDiapason service.
* @module api/WorkingDiapasonApi
* @version 1.2.1
*/
export default class WorkingDiapasonApi {

    /**
    * Constructs a new WorkingDiapasonApi. 
    * @alias module:api/WorkingDiapasonApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the clientClientIDMasterMasterIDWorkingDiapasonGet operation.
     * @callback module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение расписания мастера
     * Store *WorkingDiapason* entity
     * @param {Number} masterID Id мастера
     * @param {Number} clientID ID салона
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Как много элементов должно возвращаться за один запрос (default to 25)
     * @param {Number} opts.offset Смещение от первого (default to 0)
     * @param {String} opts.dateStart Начало периода
     * @param {String} opts.dateEnd Конец периода
     * @param {module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    clientClientIDMasterMasterIDWorkingDiapasonGet(masterID, clientID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'masterID' is set
      if (masterID === undefined || masterID === null) {
        throw new Error("Missing the required parameter 'masterID' when calling clientClientIDMasterMasterIDWorkingDiapasonGet");
      }
      // verify the required parameter 'clientID' is set
      if (clientID === undefined || clientID === null) {
        throw new Error("Missing the required parameter 'clientID' when calling clientClientIDMasterMasterIDWorkingDiapasonGet");
      }

      let pathParams = {
        'masterID': masterID,
        'clientID': clientID
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'date_start': opts['dateStart'],
        'date_end': opts['dateEnd']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;
      return this.apiClient.callApi(
        '/client/{clientID}/master/{masterID}/working-diapason', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientIDMasterMasterIDWorkingDiapasonPost operation.
     * @callback module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {module:model/WorkingDiapason} workingDiapason Store *WorkingDiapason* entity
     * @param {module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    clientClientIDMasterMasterIDWorkingDiapasonPost(workingDiapason, callback) {
      let postBody = workingDiapason;
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientIDMasterMasterIDWorkingDiapasonPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuthMaster'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/client/{clientID}/master/{masterID}/working-diapason', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDelete operation.
     * @callback module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {Number} masterID Id мастера
     * @param {Number} clientID ID салона
     * @param {Number} workingDiapasonID Id requested WorkingDiapason
     * @param {module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDelete(masterID, clientID, workingDiapasonID, callback) {
      let postBody = null;
      // verify the required parameter 'masterID' is set
      if (masterID === undefined || masterID === null) {
        throw new Error("Missing the required parameter 'masterID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDelete");
      }
      // verify the required parameter 'clientID' is set
      if (clientID === undefined || clientID === null) {
        throw new Error("Missing the required parameter 'clientID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDelete");
      }
      // verify the required parameter 'workingDiapasonID' is set
      if (workingDiapasonID === undefined || workingDiapasonID === null) {
        throw new Error("Missing the required parameter 'workingDiapasonID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDDelete");
      }

      let pathParams = {
        'masterID': masterID,
        'clientID': clientID,
        'workingDiapasonID': workingDiapasonID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuthMaster'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/client/{clientID}/master/{masterID}/working-diapason/{workingDiapasonID}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGet operation.
     * @callback module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Получение деталей временного отрезка
     * 
     * @param {Number} masterID Id мастера
     * @param {Number} clientID ID салона
     * @param {Number} workingDiapasonID Id requested WorkingDiapason
     * @param {module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGet(masterID, clientID, workingDiapasonID, callback) {
      let postBody = null;
      // verify the required parameter 'masterID' is set
      if (masterID === undefined || masterID === null) {
        throw new Error("Missing the required parameter 'masterID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGet");
      }
      // verify the required parameter 'clientID' is set
      if (clientID === undefined || clientID === null) {
        throw new Error("Missing the required parameter 'clientID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGet");
      }
      // verify the required parameter 'workingDiapasonID' is set
      if (workingDiapasonID === undefined || workingDiapasonID === null) {
        throw new Error("Missing the required parameter 'workingDiapasonID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDGet");
      }

      let pathParams = {
        'masterID': masterID,
        'clientID': clientID,
        'workingDiapasonID': workingDiapasonID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/client/{clientID}/master/{masterID}/working-diapason/{workingDiapasonID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatch operation.
     * @callback module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {Number} masterID Id мастера
     * @param {Number} clientID ID салона
     * @param {Number} workingDiapasonID Id requested WorkingDiapason
     * @param {module:model/WorkingDiapason} workingDiapason Optional description in *Markdown*
     * @param {module:api/WorkingDiapasonApi~clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatch(masterID, clientID, workingDiapasonID, workingDiapason, callback) {
      let postBody = workingDiapason;
      // verify the required parameter 'masterID' is set
      if (masterID === undefined || masterID === null) {
        throw new Error("Missing the required parameter 'masterID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatch");
      }
      // verify the required parameter 'clientID' is set
      if (clientID === undefined || clientID === null) {
        throw new Error("Missing the required parameter 'clientID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatch");
      }
      // verify the required parameter 'workingDiapasonID' is set
      if (workingDiapasonID === undefined || workingDiapasonID === null) {
        throw new Error("Missing the required parameter 'workingDiapasonID' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatch");
      }
      // verify the required parameter 'workingDiapason' is set
      if (workingDiapason === undefined || workingDiapason === null) {
        throw new Error("Missing the required parameter 'workingDiapason' when calling clientClientIDMasterMasterIDWorkingDiapasonWorkingDiapasonIDPatch");
      }

      let pathParams = {
        'masterID': masterID,
        'clientID': clientID,
        'workingDiapasonID': workingDiapasonID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        _method: "PATCH"
      };

      let authNames = ['bearerAuthMaster'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/client/{clientID}/master/{masterID}/working-diapason/{workingDiapasonID}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
